version: '3'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    ports:
      - "9300:9300"
    volumes:
      - /home/ubuntu/csvserver/inputdata/inputFile:/csvserver/inputdata
    env_file:
      - /home/ubuntu/csvserver/csvserver.env

  prometheus:
    image: prom/prometheus:v2.45.2
    ports:
      - "9090:9090"
    volumes:
      - /home/ubuntu/csvserver/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - csvserver
